### ISSUE TITLE
dropping too many rows of data- possible solution!

### ISSUE THREAD

**Issue by wetlandsDiane** [utah-geological-survey/loggerloader#47]
I found an issue with rows being erroneously dropped in the jumpfix function. I found that some records were missing from the Turkey site after running the data through loggerloader and then manually processed the data to try to isolate what was going on.

The jumpfix function drops duplicates like this:

df1 = df1.sort_index().drop_duplicates()

I created a new version of the function that just looks at duplicates in the index and prints a message if duplicates are dropped:

df_temp = df.copy(deep=True).sort_index()
    df1 = df_temp[~df_temp.index.duplicated(keep='first')]
    if df1.shape[0] != df_temp.shape[0]:
        print(f'Dropped {df_temp.shape[0]-df1.shape[0]} records')

Note that I am unclear **why** drop_duplicates() doesn't work as I would expect. But using that command drop_duplicates() dropped about 2000 records that I don't think need to be dropped. These rows that were dropped, however, did not seem like exact duplicates of one another.

**Comment by inkenbrandt** [comment]
Fork a version and do a pull request and I will merge the changes.  Let me know if you need help.
